# Generated by Django 4.0.1 on 2022-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_rename_tools_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_tools',
            field=models.ManyToManyField(to='CRM.Tool', verbose_name='Дополнительная техника'),
        ),
    ]
