# Generated by Django 4.0.1 on 2022-01-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_qtype_question_wizard_step_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(editable=False, max_length=200)),
                ('name', models.CharField(max_length=200, verbose_name='Имя Фамилия')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('teleg', models.CharField(max_length=200, verbose_name='Телеграм')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.qtype', verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='wizard_step',
            name='qustions',
            field=models.ManyToManyField(to='CRM.Question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
