# Generated by Django 4.0.1 on 2022-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_gender_user_question_q_type_wizard_step_qustions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.user', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=200, verbose_name='Должность'),
        ),
    ]
