# Generated by Django 4.0.1 on 2022-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_project_manager_user_gender_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('caption', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('functions', models.TextField(max_length=3000, verbose_name='Функции')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wizard_step',
            name='descriptor',
            field=models.CharField(max_length=1000, verbose_name='Дескриптор'),
        ),
    ]
