# Generated by Django 4.0.1 on 2022-01-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_position_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.position', verbose_name='Должность'),
        ),
    ]
