# Generated by Django 4.0.1 on 2022-01-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
    ]
