# Generated by Django 4.0.1 on 2022-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
