# Generated by Django 4.0.1 on 2022-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(to='CRM.User', verbose_name='Пользователи'),
        ),
    ]
