# Generated by Django 4.0.1 on 2022-01-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_usergroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.CharField(default='', max_length=150),
        ),
    ]
