# Generated by Django 4.0.1 on 2022-01-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(max_length=20, verbose_name='Дата рождения'),
        ),
    ]
