# Generated by Django 4.0.1 on 2022-01-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status_type', verbose_name='тип статуса')),
            ],
        ),
    ]
