# Generated by Django 4.0.1 on 2022-01-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_resource_resources_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='r_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.resources_type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
