# Generated by Django 4.0.1 on 2022-02-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_alter_project_construct_alter_project_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Отображаемое имя проекта'),
        ),
    ]
