# Generated by Django 4.0.1 on 2022-02-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0026_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=50, verbose_name='Наименование бота')),
                ('tgbot_token', models.CharField(max_length=50, verbose_name='Telegram API токен')),
                ('start_message', models.TextField(verbose_name='Текст приветственного сообщения на команду "/start"')),
            ],
        ),
    ]
