# Generated by Django 4.0.1 on 2022-02-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0027_bot_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Текст записи')),
                ('name', models.CharField(default='Потенциальный клиент', max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=50, verbose_name='')),
                ('kitchen_type', models.CharField(choices=[('C', 'Угловая'), ('P', 'П образная'), ('L', 'Прямая'), ('I', 'Островная')], max_length=2, verbose_name='')),
                ('material', models.CharField(default='', max_length=50, verbose_name='')),
                ('due_done', models.CharField(default='', max_length=50, verbose_name='')),
                ('pay_type', models.CharField(default='', max_length=50, verbose_name='')),
                ('present', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
