# Generated by Django 4.0.1 on 2022-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0028_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='due_done',
            field=models.CharField(default='', max_length=50, verbose_name='Когда планирует заказывать'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='kitchen_type',
            field=models.CharField(choices=[('C', 'Угловая'), ('P', 'П образная'), ('L', 'Прямая'), ('I', 'Островная')], max_length=2, verbose_name='Тип кухни'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='material',
            field=models.CharField(default='', max_length=50, verbose_name='Материал фасада'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='pay_type',
            field=models.CharField(default='', max_length=50, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='present',
            field=models.CharField(max_length=50, verbose_name='Выбранный подарок'),
        ),
    ]
