# Generated by Django 4.0.1 on 2022-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0029_alter_client_contact_due_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='due_done',
            field=models.CharField(default='Просто интересуюсь', max_length=50, verbose_name='Когда планирует заказывать'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='material',
            field=models.CharField(default='Помогите выбрать', max_length=50, verbose_name='Материал фасада'),
        ),
        migrations.AlterField(
            model_name='client_contact',
            name='pay_type',
            field=models.CharField(default='Картой', max_length=50, verbose_name='Оплата'),
        ),
    ]
