# Generated by Django 4.0.1 on 2022-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0030_alter_client_contact_due_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='caption',
            field=models.CharField(max_length=150, verbose_name='Текст записи'),
        ),
    ]
