# Generated by Django 4.0.1 on 2022-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0031_alter_client_contact_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='kitchen_type',
            field=models.CharField(choices=[('U', 'Не определился'), ('C', 'Угловая'), ('P', 'П образная'), ('L', 'Прямая'), ('I', 'Островная')], default='U', max_length=2, verbose_name='Тип кухни'),
        ),
    ]
